### PR TITLE
Improved Java compatibility and migrated app module to Kotlin

### LINKED ISSUE #14: Crashes app after going to background
OnPause of my activity I do:
```
    if (nearDiscovery.isDiscovering) {
      nearDiscovery.stopDiscovery()
    }
    if (nearDiscovery.isDiscoverable) {
      nearDiscovery.makeNonDiscoverable()
    }
    if (nearConnect.isReceiving) {
      nearConnect.stopReceiving(false)
    }
```

but still it crashes with this error:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent         at com.adroitandroid.near.connect.server.TcpServerService.onStartCommand(TcpServerService.kt)
```

### PR DESCRIPTION
**Pull request by DatL4g**
Fixes #14 and an issue when calling makeDiscoverable with one parameter only

### CODE REVIEW

**Comment by DatL4g** [comment]
@adroitandroid 
would be nice if you accept the pull request and merge for improvements for java users

**Comment by adroitandroid** [comment]
will check by Wednesday and merge, thanks

**Comment by DatL4g** [comment]
@adroitandroid 
Did you check it yet?

**Comment by DatL4g** [comment]
@adroitandroid 
Thanks for merging
You should create a new release so it's easier for people to include this in their project otherwise they have to get it based on the commits from jitpack

**Pull request merged**
